name: mlops-project
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup CML
        uses: iterative/setup-cml@v1

      - name: Train model
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          python train.py

      - name: Write CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Post reports as comments in GitHub PRs
          echo "## Metrics" >> report.md
          cat evaluation_results.txt >> report.md
          cml comment create report.md
