name: mlops-workflow-name
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup CML
        uses: iterative/setup-cml@v1

      - name: Train model
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          python train.py

      - name: Write CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Create a Markdown formatted comment
          echo "## Metrics" >> report.md
          echo "Accuracy for Random Forest: 0.8839779005524862" >> report.md
          echo "Accuracy for XGBoost: 0.8928176795580111" >> report.md
          cml comment create report.md
